# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Ubuntu CI

on:
  push:
    branches:
      - "**"   # Triggers on push to any branch, including new ones
    tags:
      - "*"    # Triggers on push to any tag
  pull_request:
  schedule:
    - cron: '30 2 * * 1'  # Every Monday at 2:30 AM UTC

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install rfinder
        run: uv sync

      - name: Lint with Ruff
        run: |
          uv run ruff check rfinder --show-fixes

      - name: Format check with Ruff
        run: |
          uv run ruff format rfinder --check --line-length 120

      - name: Test with pytest
        run: uv run pytest rfinder/tests/ -v

      - name: Download test dataset
        run: curl https://ratt-public-data.s3.af-south-1.amazonaws.com/test-data/HLTau_B6cont.calavg.tav300s.tar.xz | tar xJf -

      - name: Test rfinder command
        run: |
          uv run rfinder --help

      - name: Run end to end test
        run: |
          uv run rfinder -i HLTau_B6cont.calavg.tav300s -fl 0 -tel meerkat -l test
